# Homework #1

1. **Calculate the inner product of vectors**
   $\begin{pmatrix} 2 \\ 3 \end{pmatrix}$ and $\begin{pmatrix} -4 \\ 1 \end{pmatrix}$.

*Your Python solution*

In [2]:
import numpy as np

# Define the vectors
vector1 = np.array([2, 3])
vector2 = np.array([-4, 1])

# Compute the inner product
inner_product = np.dot(vector1, vector2)

print("The inner product of the vectors is:", inner_product)

The inner product of the vectors is: -5


*Your handwritten solution.* 

2. **Normalize the vector**
   $\begin{pmatrix} 3 \\ -4 \end{pmatrix}$.

*Your Python solution*

In [3]:
import numpy as np

# Define the vector
vector = np.array([3, -4])

# Calculate the magnitude of the vector
magnitude = np.linalg.norm(vector)

# Normalize the vector
normalized_vector = vector / magnitude

print("The normalized vector is:", normalized_vector)


The normalized vector is: [ 0.6 -0.8]


*Your handwritten solution.* 

3. **Find the cross product of**
   $\begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix}$ and $\begin{pmatrix} 4 \\ 5 \\ 6 \end{pmatrix}$.
   *Hint:* Remember the determinant expansion method.

*Your Python solution* 
> see here: https://numpy.org/doc/stable/reference/generated/numpy.cross.html


In [4]:
# Define the vectors (assuming the third component is 0 for 2D vectors)
vector1 = np.array([1, 2, 3])  # Extend the 2D vector (2, 3) to 3D
vector2 = np.array([4, 5, 6])  # Extend the 2D vector (-4, 1) to 3D

# Compute the cross product
cross_product = np.cross(vector1, vector2)

print("The cross product of the vectors is:", cross_product)


The cross product of the vectors is: [-3  6 -3]


*Your handwritten solution.* 

4. **Compute the determinant of the matrix**
   $\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$.

*Your Python solution*

In [5]:
# Define the matrix
matrix = np.array([[1, 2], [3, 4]])

# Calculate the determinant
determinant = np.linalg.det(matrix)

# Rounding the final answer
print("The determinant of the matrix is:", determinant.round())

The determinant of the matrix is: -2.0


*Your handwritten solution.* 

5. **Compute the _tensor_ product of vectors**
   $\begin{pmatrix} 1 \\ 2 \end{pmatrix}$ and $\begin{pmatrix} 3 \\ 4 \end{pmatrix}$.
   *Hint:* The result should be a $4 \times 1$ vector.

*Your Python solution*

In [6]:
# Define the vectors
v = np.array([1, 2])
w = np.array([3, 4])

# Compute the tensor product (Kronecker product)
tensor_product = np.kron(v, w)

# Reshape the tensor product to a 4x1 matrix for display
tensor_product_matrix = tensor_product.reshape(-1, 1)

print("The tensor product of the vectors is:\n")
print(tensor_product_matrix)

The tensor product of the vectors is:

[[3]
 [4]
 [6]
 [8]]


*Your handwritten solution.* 

6. **Compute the _dyadic_ product of vectors**
   $\begin{pmatrix} 1 \\ 2 \end{pmatrix}$ and $\begin{pmatrix} 3 \\ 4 \end{pmatrix}$.
   *Hint:* The result should be a $2 \times 2$ matrix.

*Your Python solution*

In [7]:
# Define the vectors
v = np.array([[1], [2]])  # Column vector
w = np.array([[3, 4]])    # Row vector

# Compute the dyadic product
dyadic_product = np.dot(v, w)

print("The dyadic product of the vectors is:\n")
print(dyadic_product)

The dyadic product of the vectors is:

[[3 4]
 [6 8]]


*Your handwritten solution.* 

7. **Calculate the inner product of complex vectors**
   $\begin{pmatrix} 2i \\ 4 \end{pmatrix}$ and $\begin{pmatrix} 3 - i \\ i \end{pmatrix}$.
   *Hint:* Recall the conjugate transpose for complex numbers.

*Your Python solution*

In [8]:
# Define the complex vectors
v = np.array([2j, 4])
w = np.array([3 - 1j, 1j])

# Compute the inner product (conjugate transpose of v dot w)
inner_product = np.vdot(v, w)

print("The inner product of the complex vectors is:", inner_product)

The inner product of the complex vectors is: (-2-2j)


*Your handwritten solution.* 

8. **Normalize the complex vector**
    $\begin{pmatrix} i \\ 1 - i \end{pmatrix}$.
    *Hint:* Remember the magnitude of a complex number.

*Your Python solution*

In [10]:
# Define the complex vector
v = np.array([1j, 1 - 1j])

# Calculate the magnitude (norm) of the vector
norm = np.linalg.norm(v)

# Normalize the vector
normalized_v = v / norm

# Format the result for printing
formatted_result = np.array2string(normalized_v, separator=', ', formatter={'complexfloat': lambda x: f'{x:.2f}'})

print("The normalized complex vector is:")
print(formatted_result)

The normalized complex vector is:
[0.00+0.58j, 0.58-0.58j]


*Your handwritten solution.* 

9. **Find the determinant of the complex matrix**
    $\begin{pmatrix} i & 1 - i \\ 2 + i & 3 \end{pmatrix}$.
    *Hint:* Same formula, but now consider complex arithmetic.

*Your Python solution*

In [12]:
# Define the complex matrix
A = np.array([[1j, 1 - 1j], [2 + 1j, 3]])

# Calculate the determinant
det_A = np.linalg.det(A)

# Format the output to two decimal places for both real and imaginary parts
formatted_det = f'{det_A.real:.2f} + {det_A.imag:.2f}i'

print("The determinant of the complex matrix is:")
print(formatted_det)

The determinant of the complex matrix is:
-3.00 + 4.00i


*Your handwritten solution.* 

10. **Define the following five matrices in Python (NumPy)**:

\begin{align}
I = \begin{pmatrix} 1&0 \\ 0&1 \end{pmatrix}, \quad
X = \begin{pmatrix} 0&1 \\ 1&0 \end{pmatrix}, \quad
Y = \begin{pmatrix} 0&i \\ -i&0 \end{pmatrix}, \quad
Z = \begin{pmatrix} 1&0 \\ 0&-1 \end{pmatrix}, \quad
H = \frac{1}{\sqrt{2}} \begin{pmatrix} 1&1 \\ 1&-1 \end{pmatrix}
\end{align}

These are five of the most common single qubit gates used in quantum computing, and they will be used repeatedly. 

#### Write Python code to compute the following matrix multiplications:

1. $XY$
2. $YX$
3. $YZ$
4. $ZY$
5. $HX$
6. $YH$
7. $XYZ$
8. $YZX$
9. $ZXY$
10. $XHY$

*Your Python solution*

In [14]:
# Define the quantum gates as matrices
I = np.array([[1, 0], [0, 1]])
X = np.array([[0, 1], [1, 0]])
Y = np.array([[0, -1j], [1j, 0]])
Z = np.array([[1, 0], [0, -1]])
H = (1/np.sqrt(2)) * np.array([[1, 1], [1, -1]])

# Perform the matrix multiplications
results = {
    'XY': np.dot(X, Y),
    'YX': np.dot(Y, X),
    'YZ': np.dot(Y, Z),
    'ZY': np.dot(Z, Y),
    'HX': np.dot(H, X),
    'YH': np.dot(Y, H),
    'YXZ': np.dot(Y, np.dot(X, Z)),
    'ZYX': np.dot(Z, np.dot(Y, X)),
    'XYH': np.dot(X, np.dot(Y, H)),
    'XHY': np.dot(X, np.dot(H, Y)),
}

# Function to print matrices cleanly with their labels
def print_results(results):
    for name, matrix in results.items():
        print(f"Matrix multiplication result for {name}:")
        print(matrix)
        print("\n")

# Print the matrices
print_results(results)

Matrix multiplication result for XY:
[[0.+1.j 0.+0.j]
 [0.+0.j 0.-1.j]]


Matrix multiplication result for YX:
[[0.-1.j 0.+0.j]
 [0.+0.j 0.+1.j]]


Matrix multiplication result for YZ:
[[0.+0.j 0.+1.j]
 [0.+1.j 0.+0.j]]


Matrix multiplication result for ZY:
[[0.+0.j 0.-1.j]
 [0.-1.j 0.+0.j]]


Matrix multiplication result for HX:
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


Matrix multiplication result for YH:
[[0.-0.70710678j 0.+0.70710678j]
 [0.+0.70710678j 0.+0.70710678j]]


Matrix multiplication result for YXZ:
[[0.-1.j 0.+0.j]
 [0.+0.j 0.-1.j]]


Matrix multiplication result for ZYX:
[[0.-1.j 0.+0.j]
 [0.+0.j 0.-1.j]]


Matrix multiplication result for XYH:
[[0.+0.70710678j 0.+0.70710678j]
 [0.-0.70710678j 0.+0.70710678j]]


Matrix multiplication result for XHY:
[[0.-0.70710678j 0.-0.70710678j]
 [0.+0.70710678j 0.-0.70710678j]]
